# Generated by Django 3.0.4 on 2020-04-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiaRecords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='latitude',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='state',
            name='longitude',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
