# Generated by Django 3.0.4 on 2020-04-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indiaRecords', '0002_auto_20200415_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='statecode',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
