# Generated by Django 3.0.4 on 2020-04-15 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indiaRecords', '0003_auto_20200415_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='deltaConfirmed',
            new_name='deltaconfirmed',
        ),
    ]
